
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "7000:7000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=shop_cd.settings
      - MEDIA_ROOT=/app/
    restart: unless-stopped