# Generated by Django 5.1.5 on 2025-01-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_options_remove_product_popularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularityvote',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
